# Generated by Django 4.2 on 2023-05-03 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('quiz', '0001_initial'), ('quiz', '0002_quiz_slug'), ('quiz', '0003_answer_useranswer_remove_answertext_question_and_more'), ('quiz', '0004_alter_quiz_slug'), ('quiz', '0005_remove_answer_question_question_answerds'), ('quiz', '0006_rename_answer_answerd_rename_useranswer_useranswerd_and_more'), ('quiz', '0007_alter_useranswerd_unique_together_and_more'), ('quiz', '0008_rename_answerd_answer_rename_useranswerd_useranswer_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('answers', models.ManyToManyField(related_name='answers', to='quiz.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('questions', models.ManyToManyField(related_name='questions', to='quiz.question')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_answer', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('user', 'answer')},
            },
        ),
    ]
