# Generated by Django 4.2 on 2023-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_squashed_0008_rename_answerd_answer_rename_useranswerd_useranswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('SINGLE_SELECT', 'Single select'), ('MULTI_SELECT', 'Multi select')], default='SINGLE_SELECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(),
        ),
    ]
