# Generated by Django 4.2 on 2023-05-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_quiz_type_alter_quiz_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_type',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SINGLE_SELECT', 'Single select'), ('MULTI_SELECT', 'Multi select')], default='SINGLE_SELECT', max_length=20),
        ),
    ]
